#!/bin/bash

for ip in 192.xxx8.25.247    10.52.7.6    10.52.7.22    10.52.7.42    10.71.66.2    10.52.7.35    10.52.7.34    10.52.7.30    10.52.7.18    10.52.7.10    192.xxx8.100.11    10.52.7.26    10.52.66.40 ;
do ssh oracle@$ip <<EOF
sqlplus / as sysdba <<EOF
col col_name format A40;
set linesize 10000;
set pagesize 50000;
select  * from username.patches p WHERE ROWNUM < 2  order by P.DATE_APPLYED desc;
select status, provider_name, ip_addres, db_name from username.table where status>0;
quit
EOF;
exit
EOF
done
done#!/bin/bash

for ip in  172.xxx.27.49 172.xxx.61.225 172.xxx.23.77 172.xxx.xxx6.65  172.xxx.xxx.33 172.xxx.25.129 172.xxx.55.69 172.xxx.154.133;
do ssh root@$ip <<EOF
su - oracle;
sqlplus / as sysdba <<EOF
execute dbms_scheduler.disable('username.JOB_MESSAGE_VER');
quit
EOF;
exit
EOF
done
oracle

j=1;for i in `ls file*`;do  mv $i  file1$(($j+1)).csv; j=$(($j+1)); done;
for i in `ls file2*`;do sed -i 's/\r//' $i; done;
